# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrs_1.xdc

# IP: ip/IP006_uart_reg32_0_1/IP006_uart_reg32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IP006_uart_reg32_0 || ORIG_REF_NAME==IP006_uart_reg32_0} -quiet] -quiet

# IP: ip/VGA_0_2/VGA_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VGA_0 || ORIG_REF_NAME==VGA_0} -quiet] -quiet

# IP: ip/VGA_0_2/src/VGA_clk_wiz_0_0/VGA_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VGA_clk_wiz_0_0 || ORIG_REF_NAME==VGA_clk_wiz_0_0} -quiet] -quiet

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/vio_0_1/vio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet

# XDC: ip/VGA_0_2/src/VGA_clk_wiz_0_0/VGA_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==VGA_clk_wiz_0_0 || ORIG_REF_NAME==VGA_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/VGA_0_2/src/VGA_clk_wiz_0_0/VGA_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==VGA_clk_wiz_0_0 || ORIG_REF_NAME==VGA_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/VGA_0_2/src/VGA_clk_wiz_0_0/VGA_clk_wiz_0_0_ooc.xdc

# XDC: ip/VGA_0_2/src/VGA_ooc.xdc

# XDC: ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila_0/ila_0_ooc.xdc

# XDC: ip/vio_0_1/vio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_0 || ORIG_REF_NAME==vio_0} -quiet] -quiet
