# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.runs/synth_1/mic1_basys3.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.cache/wt [current_project]
set_property parent.project_path C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/emile/OneDrive/files/IPCORE_UART_MUX/src/UART_GUI_IP006_uart_reg32_0_0
  c:/Users/emile/OneDrive/files/VGA_IP_Core
  c:/Users/emile/OneDrive/files/3_ip_core_32bit
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/emile/OneDrive/files/mic-1-project/microcode.mem
  C:/Users/emile/OneDrive/files/mic-1-project/add.mem
  {C:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/VGA_Final_IPCore/VGA_Final_IPCore.srcs/sources_1/new/static_mems.mem}
  {C:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/VGA_Final_IPCore/VGA_Final_IPCore.srcs/sources_1/new/character.mem}
  {C:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/VGA_Final_IPCore/VGA_Final_IPCore.srcs/sources_1/new/data_to_address.mem}
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/alu/rtl/alu.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/control-store/rtl/control_store.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/util/rtl/debouncer.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/util/rtl/edge_detection.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/imports/rtl/main_memory.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/new/memory_manager.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/rtl/mic1.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/rtl/mic1_soc.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/shifter/rtl/shifter.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/util/rtl/synchronizer.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/uart/rtl/uart_baud.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/uart/rtl/uart_rx.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/uart/rtl/uart_tx.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/rtl/defines_add.sv
  C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/rtl/mic1_basys3.sv
}
read_verilog -library xil_defaultlib C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/imports/src/MUX_DEMUX.v
read_ip -quiet C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/IP006_uart_reg32_0_1/IP006_uart_reg32_0.xci

read_ip -quiet C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_0_2/VGA_0.xci
set_property used_in_implementation false [get_files -all c:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_0_2/src/VGA_clk_wiz_0_0/VGA_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_0_2/src/VGA_clk_wiz_0_0/VGA_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_0_2/src/VGA_clk_wiz_0_0/VGA_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_0_2/src/VGA_ooc.xdc]

read_ip -quiet C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/vio_0_1/vio_0.xci
set_property used_in_implementation false [get_files -all c:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/vio_0_1/vio_0.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/constrs_1/new/constrs_1.xdc
set_property used_in_implementation false [get_files C:/Users/emile/OneDrive/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/constrs_1/new/constrs_1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mic1_basys3 -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mic1_basys3.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mic1_basys3_utilization_synth.rpt -pb mic1_basys3_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
