# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/VGA_IP_0.xci
# IP: The module: 'VGA_IP_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/src/VGA_IP_clk_wiz_0_0/VGA_IP_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VGA_IP_clk_wiz_0_0 || ORIG_REF_NAME==VGA_IP_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/src/VGA_IP_clk_wiz_0_0/VGA_IP_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==VGA_IP_clk_wiz_0_0 || ORIG_REF_NAME==VGA_IP_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/src/VGA_IP_clk_wiz_0_0/VGA_IP_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==VGA_IP_clk_wiz_0_0 || ORIG_REF_NAME==VGA_IP_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/src/VGA_IP_clk_wiz_0_0/VGA_IP_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/src/VGA_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_IP_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/VGA_IP_0.xci
# IP: The module: 'VGA_IP_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/src/VGA_IP_clk_wiz_0_0/VGA_IP_clk_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VGA_IP_clk_wiz_0_0 || ORIG_REF_NAME==VGA_IP_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/src/VGA_IP_clk_wiz_0_0/VGA_IP_clk_wiz_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==VGA_IP_clk_wiz_0_0 || ORIG_REF_NAME==VGA_IP_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/src/VGA_IP_clk_wiz_0_0/VGA_IP_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==VGA_IP_clk_wiz_0_0 || ORIG_REF_NAME==VGA_IP_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/src/VGA_IP_clk_wiz_0_0/VGA_IP_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/emile/OneDrive/Unief/Erasmus/Courses/ECE Project/files/mic-1-project/verilog/top-level/top_level_basys3.srcs/sources_1/ip/VGA_IP_0/src/VGA_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_IP_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
