-- VHDL Entity IP006_lib.bus_bridge_32.symbol
--
-- Created:
--          by - lamplpat.UNKNOWN (M00159)
--          at - 11:45:08 08.03.2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY bus_bridge_32 IS
   PORT( 
      bus_ack     : IN     std_logic;
      bus_din     : IN     std_logic_vector (31 DOWNTO 0);
      bus_grant   : IN     std_logic;
      clk         : IN     std_logic;
      cmd         : IN     std_logic_vector (7 DOWNTO 0);
      cmd_we      : IN     std_logic;
      reset       : IN     std_logic;
      slv_cs      : IN     std_logic;
      slv_din     : IN     std_logic;
      slv_we      : IN     std_logic;
      tx_ack      : IN     std_logic;
      bus_addr    : OUT    std_logic_vector ( 15 DOWNTO 0 );
      bus_dout    : OUT    std_logic_vector (31 DOWNTO 0);
      bus_rd      : OUT    std_logic;
      bus_request : OUT    std_logic;
      bus_we      : OUT    std_logic;
      response    : OUT    std_logic_vector (7 DOWNTO 0);
      response_en : OUT    std_logic;
      slv_ack     : OUT    std_logic
   );

-- Declarations

END bus_bridge_32 ;

--
-- VHDL Architecture IP006_lib.bus_bridge_32.fsm
--
-- Created:
--          by - lamplpat.UNKNOWN (M00159)
--          at - 11:49:49 08.03.2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
 
ARCHITECTURE fsm OF bus_bridge_32 IS

   -- Architecture Declarations
   signal cmd_write: std_logic;
   signal cmd_fifowrite: std_logic;
   signal cmd_blockwrite: std_logic;
   signal cmd_read: std_logic;
   signal cmd_blockread: std_logic;
   signal cmd_fiforead: std_logic;
   signal cmd_escape: std_logic;
   signal cmd_par: std_logic;
   signal num: std_logic_vector(7 downto 0);
   signal nibble: std_logic_vector(3 downto 0);
   signal response_nibble: std_logic_vector(3 downto 0);
   signal response_nibble_rx: std_logic_vector(3 downto 0);
   signal response_nibble_tx: std_logic_vector(3 downto 0);
   signal response_en_rx, response_en_tx: std_logic;
   signal bus_addr_int: std_logic_vector(bus_addr'range);
   signal bus_dout_int: std_logic_vector(bus_dout'range);
   signal response_int: std_logic_vector(response'range);
   signal bus_din_tmp: std_logic_vector(bus_dout'range);
   signal data_en: std_logic;
   signal lock_rx, lock_tx: std_logic;
   signal slv_txd: std_logic_vector(bus_dout'range);
   
   function to_ascii(arg: std_logic_vector(7 downto 0)) return std_logic_vector is
      variable offset: std_logic_vector(7 downto 0);
      variable result:  std_logic_vector(7 downto 0);
   begin
      if arg < "00001010" then
          offset := X"30";
      else
          offset := X"37";
      end if;
      result := (arg) + offset;
      return(result);
   end to_ascii;

   TYPE RX_CSM_STATE_TYPE IS (
      s_write,
      s_addr0,
      s_addr1,
      s_data0,
      s_data1,
      s_read,
      s_addr2,
      s_addr3,
      s_data2,
      s_data3,
      s_addr4,
      s_addr5,
      s_addr6,
      s_addr7,
      s_data4,
      s_data5,
      s_data6,
      s_data7,
      s_reg,
      s_read1,
      s_addr8,
      s_addr9,
      s_addr10,
      s_addr11,
      s_num0,
      s_num1,
      s_reg1,
      s_data10,
      s_data11,
      s_data12,
      s_data13,
      s0,
      s_halt,
      s_arb0,
      s_arb1,
      s_arb2,
      s_fwrite,
      s_fwaddr0,
      s_fwaddr1,
      s_fwaddr2,
      s_fwaddr3,
      s_fwdata0,
      s_fwdata1,
      s_fwdata2,
      s_data15,
      s_arb3,
      s_escape,
      s_fwdata3,
      s_fwdata4,
      s_fwdata5,
      s_fwdata6,
      s_data8,
      s_data9,
      s_data14,
      s_data16,
      s_data17,
      s_data18,
      s_data19,
      s_data20,
      s_data21,
      s_data22,
      s_data23,
      s_data24
   );
   TYPE CSM_STATE_TYPE IS (
      s1,
      s2
   );
 
   -- Declare current and next state signals
   SIGNAL rx_csm_current_state : RX_CSM_STATE_TYPE;
   SIGNAL rx_csm_next_state : RX_CSM_STATE_TYPE;
   SIGNAL csm_current_state : CSM_STATE_TYPE;
   SIGNAL csm_next_state : CSM_STATE_TYPE;

   -- Declare any pre-registered internal signals
   SIGNAL slv_ack_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   rx_csm_clocked_proc : PROCESS ( 
      clk
   )
   -----------------------------------------------------------------
   BEGIN
      IF (clk'EVENT AND clk = '1') THEN
         IF (reset = '1') THEN
            rx_csm_current_state <= s_halt;
            -- Default Reset Values
            bus_din_tmp <= (others => '0');
            bus_dout_int <= (others => '0');
            lock_rx <= '0';
            response_en_rx <= '0';
            response_nibble_rx <= (others => '0');
         ELSE
            rx_csm_current_state <= rx_csm_next_state;
            -- Default Assignment To Internals
            response_en_rx <= '0';

            -- Combined Actions
            CASE rx_csm_current_state IS
               WHEN s_write => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(15 downto 12) <= nibble;
                  END IF;
               WHEN s_addr0 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(11 downto 8) <= nibble;
                  END IF;
               WHEN s_addr1 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(7 downto 4) <= nibble;
                  END IF;
               WHEN s_data0 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(27 downto 24) <= nibble;
                  END IF;
               WHEN s_data1 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(23 downto 20) <= nibble;
                  END IF;
               WHEN s_read => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(15 downto 12) <= nibble;
                  END IF;
               WHEN s_addr2 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(11 downto 8) <= nibble;
                  END IF;
               WHEN s_addr3 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(7 downto 4) <= nibble;
                  END IF;
               WHEN s_data2 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(27 downto 24);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data3 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(23 downto 20);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_addr4 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(3 downto 0) <= nibble;
                  END IF;
               WHEN s_addr5 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(3 downto 0) <= nibble;
                  END IF;
               WHEN s_addr6 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(31 downto 28) <= nibble;
                  END IF;
               WHEN s_addr7 => 
                  IF (bus_ack = '1') THEN 
                     bus_din_tmp <= bus_din;
                  END IF;
               WHEN s_data4 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(19 downto 16);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data5 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(19 downto 16) <= nibble;
                  END IF;
               WHEN s_data7 => 
                  IF (tx_ack = '1') THEN 
                     lock_rx <= '0';
                  END IF;
               WHEN s_reg => 
                  IF (lock_tx = '0') THEN 
                     response_nibble_rx <= bus_din_tmp(31 downto 28);
                     response_en_rx <= '1';
                     lock_rx <= '1';
                  END IF;
               WHEN s_read1 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(15 downto 12) <= nibble;
                  END IF;
               WHEN s_addr8 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(11 downto 8) <= nibble;
                  END IF;
               WHEN s_addr9 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(7 downto 4) <= nibble;
                  END IF;
               WHEN s_addr10 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(3 downto 0) <= nibble;
                  END IF;
               WHEN s_addr11 => 
                  IF (cmd_we = '1') THEN 
                     num(7 downto 4) <= nibble;
                  END IF;
               WHEN s_num0 => 
                  IF (cmd_we = '1') THEN 
                     num(3 downto 0) <= nibble;
                  END IF;
               WHEN s_reg1 => 
                  IF (lock_tx = '0') THEN 
                     response_nibble_rx <= bus_din_tmp(31 downto 28);
                     response_en_rx <= '1';
                     lock_rx <= '1';
                  END IF;
               WHEN s_data10 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(27 downto 24);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data11 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(23 downto 20);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data12 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(19 downto 16);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data13 => 
                  IF (tx_ack = '1') THEN 
                     num <= num-1;
                     if cmd_par = '0' then -- increment
                        bus_addr_int <= bus_addr_int+1;
                     end if;
                  END IF;
               WHEN s0 => 
                  IF (NOT(num /= 0)) THEN 
                     lock_rx <= '0';
                  END IF;
               WHEN s_arb2 => 
                  IF (bus_ack = '1') THEN 
                     bus_din_tmp <= bus_din;
                  END IF;
               WHEN s_fwrite => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(15 downto 12) <= nibble;
                  END IF;
               WHEN s_fwaddr0 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(11 downto 8) <= nibble;
                  END IF;
               WHEN s_fwaddr1 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(7 downto 4) <= nibble;
                  END IF;
               WHEN s_fwaddr2 => 
                  IF (cmd_we = '1') THEN 
                     bus_addr_int(3 downto 0) <= nibble;
                  END IF;
               WHEN s_fwaddr3 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(31 downto 28) <= nibble;
                  END IF;
               WHEN s_fwdata0 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(27 downto 24) <= nibble;
                  END IF;
               WHEN s_fwdata1 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(23 downto 20) <= nibble;
                  END IF;
               WHEN s_fwdata2 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(19 downto 16) <= nibble;
                  END IF;
               WHEN s_arb3 => 
                  IF (bus_ack = '1') THEN 
                     bus_addr_int <= bus_addr_int+1;
                  END IF;
               WHEN s_fwdata3 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(15 downto 12) <= nibble;
                  END IF;
               WHEN s_fwdata4 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(11 downto 8) <= nibble;
                  END IF;
               WHEN s_fwdata5 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(7 downto 4) <= nibble;
                  END IF;
               WHEN s_fwdata6 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(3 downto 0) <= nibble;
                  END IF;
               WHEN s_data8 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(15 downto 12) <= nibble;
                  END IF;
               WHEN s_data9 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(11 downto 8) <= nibble;
                  END IF;
               WHEN s_data14 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(7 downto 4) <= nibble;
                  END IF;
               WHEN s_data16 => 
                  IF (cmd_we = '1') THEN 
                     bus_dout_int(3 downto 0) <= nibble;
                  END IF;
               WHEN s_data17 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(15 downto 12);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data18 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(11 downto 8);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data19 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(7 downto 4);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data20 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(3 downto 0);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data21 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(15 downto 12);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data22 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(11 downto 8);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data23 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(7 downto 4);
                     response_en_rx <= '1';
                  END IF;
               WHEN s_data24 => 
                  IF (tx_ack = '1') THEN 
                     response_nibble_rx <= bus_din_tmp(3 downto 0);
                     response_en_rx <= '1';
                  END IF;
               WHEN OTHERS =>
                  NULL;
            END CASE;

            -- Interrupts
            IF (cmd_read = '1') THEN
               NULL;
            ELSIF (cmd_write = '1') THEN
               NULL;
            ELSIF (cmd_blockread = '1') THEN
               cmd_par <= '0';
            ELSIF (cmd_fiforead = '1') THEN
               cmd_par <= '1';
            ELSIF (cmd_blockwrite = '1') THEN
               NULL;
            ELSIF (cmd_escape = '1') THEN
               NULL;
            END IF;
         END IF;
      END IF;
   END PROCESS rx_csm_clocked_proc;
 
   -----------------------------------------------------------------
   rx_csm_nextstate_proc : PROCESS ( 
      bus_ack,
      bus_grant,
      cmd_blockread,
      cmd_blockwrite,
      cmd_escape,
      cmd_fiforead,
      cmd_read,
      cmd_we,
      cmd_write,
      lock_tx,
      num,
      rx_csm_current_state,
      tx_ack
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default state assignment
      rx_csm_next_state <= rx_csm_current_state;
      CASE rx_csm_current_state IS
         WHEN s_write => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr0;
            ELSE
               rx_csm_next_state <= s_write;
            END IF;
         WHEN s_addr0 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr1;
            ELSE
               rx_csm_next_state <= s_addr0;
            END IF;
         WHEN s_addr1 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr4;
            ELSE
               rx_csm_next_state <= s_addr1;
            END IF;
         WHEN s_data0 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_data1;
            ELSE
               rx_csm_next_state <= s_data0;
            END IF;
         WHEN s_data1 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_data5;
            ELSE
               rx_csm_next_state <= s_data1;
            END IF;
         WHEN s_read => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr2;
            ELSE
               rx_csm_next_state <= s_read;
            END IF;
         WHEN s_addr2 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr3;
            ELSE
               rx_csm_next_state <= s_addr2;
            END IF;
         WHEN s_addr3 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr5;
            ELSE
               rx_csm_next_state <= s_addr3;
            END IF;
         WHEN s_data2 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data3;
            ELSE
               rx_csm_next_state <= s_data2;
            END IF;
         WHEN s_data3 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data4;
            ELSE
               rx_csm_next_state <= s_data3;
            END IF;
         WHEN s_addr4 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr6;
            ELSE
               rx_csm_next_state <= s_addr4;
            END IF;
         WHEN s_addr5 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_arb1;
            ELSE
               rx_csm_next_state <= s_addr5;
            END IF;
         WHEN s_addr6 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_data0;
            ELSE
               rx_csm_next_state <= s_addr6;
            END IF;
         WHEN s_addr7 => 
            IF (bus_ack = '1') THEN 
               rx_csm_next_state <= s_reg;
            ELSE
               rx_csm_next_state <= s_addr7;
            END IF;
         WHEN s_data4 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data17;
            ELSE
               rx_csm_next_state <= s_data4;
            END IF;
         WHEN s_data5 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_data8;
            ELSE
               rx_csm_next_state <= s_data5;
            END IF;
         WHEN s_data6 => 
            IF (bus_grant = '1') THEN 
               rx_csm_next_state <= s_arb0;
            ELSE
               rx_csm_next_state <= s_data6;
            END IF;
         WHEN s_data7 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_halt;
            ELSE
               rx_csm_next_state <= s_data7;
            END IF;
         WHEN s_reg => 
            IF (lock_tx = '0') THEN 
               rx_csm_next_state <= s_data2;
            ELSE
               rx_csm_next_state <= s_reg;
            END IF;
         WHEN s_read1 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr8;
            ELSE
               rx_csm_next_state <= s_read1;
            END IF;
         WHEN s_addr8 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr9;
            ELSE
               rx_csm_next_state <= s_addr8;
            END IF;
         WHEN s_addr9 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr10;
            ELSE
               rx_csm_next_state <= s_addr9;
            END IF;
         WHEN s_addr10 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_addr11;
            ELSE
               rx_csm_next_state <= s_addr10;
            END IF;
         WHEN s_addr11 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_num0;
            ELSE
               rx_csm_next_state <= s_addr11;
            END IF;
         WHEN s_num0 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_num1;
            ELSE
               rx_csm_next_state <= s_num0;
            END IF;
         WHEN s_num1 => 
            IF (bus_grant = '1') THEN 
               rx_csm_next_state <= s_arb2;
            ELSE
               rx_csm_next_state <= s_num1;
            END IF;
         WHEN s_reg1 => 
            IF (lock_tx = '0') THEN 
               rx_csm_next_state <= s_data10;
            ELSE
               rx_csm_next_state <= s_reg1;
            END IF;
         WHEN s_data10 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data11;
            ELSE
               rx_csm_next_state <= s_data10;
            END IF;
         WHEN s_data11 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data12;
            ELSE
               rx_csm_next_state <= s_data11;
            END IF;
         WHEN s_data12 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data21;
            ELSE
               rx_csm_next_state <= s_data12;
            END IF;
         WHEN s_data13 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s0;
            ELSE
               rx_csm_next_state <= s_data13;
            END IF;
         WHEN s0 => 
            IF (num /= 0) THEN 
               rx_csm_next_state <= s_num1;
            ELSE
               rx_csm_next_state <= s_halt;
            END IF;
         WHEN s_halt => 
            rx_csm_next_state <= s_halt;
         WHEN s_arb0 => 
            IF (bus_ack = '1') THEN 
               rx_csm_next_state <= s_halt;
            ELSE
               rx_csm_next_state <= s_arb0;
            END IF;
         WHEN s_arb1 => 
            IF (bus_grant = '1') THEN 
               rx_csm_next_state <= s_addr7;
            ELSE
               rx_csm_next_state <= s_arb1;
            END IF;
         WHEN s_arb2 => 
            IF (bus_ack = '1') THEN 
               rx_csm_next_state <= s_reg1;
            ELSE
               rx_csm_next_state <= s_arb2;
            END IF;
         WHEN s_fwrite => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwaddr0;
            ELSE
               rx_csm_next_state <= s_fwrite;
            END IF;
         WHEN s_fwaddr0 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwaddr1;
            ELSE
               rx_csm_next_state <= s_fwaddr0;
            END IF;
         WHEN s_fwaddr1 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwaddr2;
            ELSE
               rx_csm_next_state <= s_fwaddr1;
            END IF;
         WHEN s_fwaddr2 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwaddr3;
            ELSE
               rx_csm_next_state <= s_fwaddr2;
            END IF;
         WHEN s_fwaddr3 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwdata0;
            ELSE
               rx_csm_next_state <= s_fwaddr3;
            END IF;
         WHEN s_fwdata0 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwdata1;
            ELSE
               rx_csm_next_state <= s_fwdata0;
            END IF;
         WHEN s_fwdata1 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwdata2;
            ELSE
               rx_csm_next_state <= s_fwdata1;
            END IF;
         WHEN s_fwdata2 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwdata3;
            ELSE
               rx_csm_next_state <= s_fwdata2;
            END IF;
         WHEN s_data15 => 
            IF (bus_grant = '1') THEN 
               rx_csm_next_state <= s_arb3;
            ELSE
               rx_csm_next_state <= s_data15;
            END IF;
         WHEN s_arb3 => 
            IF (bus_ack = '1') THEN 
               rx_csm_next_state <= s_fwaddr3;
            ELSE
               rx_csm_next_state <= s_arb3;
            END IF;
         WHEN s_escape => 
            rx_csm_next_state <= s_escape;
         WHEN s_fwdata3 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwdata4;
            ELSE
               rx_csm_next_state <= s_fwdata3;
            END IF;
         WHEN s_fwdata4 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwdata5;
            ELSE
               rx_csm_next_state <= s_fwdata4;
            END IF;
         WHEN s_fwdata5 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_fwdata6;
            ELSE
               rx_csm_next_state <= s_fwdata5;
            END IF;
         WHEN s_fwdata6 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_data15;
            ELSE
               rx_csm_next_state <= s_fwdata6;
            END IF;
         WHEN s_data8 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_data9;
            ELSE
               rx_csm_next_state <= s_data8;
            END IF;
         WHEN s_data9 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_data14;
            ELSE
               rx_csm_next_state <= s_data9;
            END IF;
         WHEN s_data14 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_data16;
            ELSE
               rx_csm_next_state <= s_data14;
            END IF;
         WHEN s_data16 => 
            IF (cmd_we = '1') THEN 
               rx_csm_next_state <= s_data6;
            ELSE
               rx_csm_next_state <= s_data16;
            END IF;
         WHEN s_data17 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data18;
            ELSE
               rx_csm_next_state <= s_data17;
            END IF;
         WHEN s_data18 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data19;
            ELSE
               rx_csm_next_state <= s_data18;
            END IF;
         WHEN s_data19 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data20;
            ELSE
               rx_csm_next_state <= s_data19;
            END IF;
         WHEN s_data20 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data7;
            ELSE
               rx_csm_next_state <= s_data20;
            END IF;
         WHEN s_data21 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data22;
            ELSE
               rx_csm_next_state <= s_data21;
            END IF;
         WHEN s_data22 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data23;
            ELSE
               rx_csm_next_state <= s_data22;
            END IF;
         WHEN s_data23 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data24;
            ELSE
               rx_csm_next_state <= s_data23;
            END IF;
         WHEN s_data24 => 
            IF (tx_ack = '1') THEN 
               rx_csm_next_state <= s_data13;
            ELSE
               rx_csm_next_state <= s_data24;
            END IF;
         WHEN OTHERS =>
            rx_csm_next_state <= s_halt;
      END CASE;

      -- Interrupts
      IF (cmd_read = '1') THEN
         rx_csm_next_state <= s_read;
      ELSIF (cmd_write = '1') THEN
         rx_csm_next_state <= s_write;
      ELSIF (cmd_blockread = '1') THEN
         rx_csm_next_state <= s_read1;
      ELSIF (cmd_fiforead = '1') THEN
         rx_csm_next_state <= s_read1;
      ELSIF (cmd_blockwrite = '1') THEN
         rx_csm_next_state <= s_fwrite;
      ELSIF (cmd_escape = '1') THEN
         rx_csm_next_state <= s_escape;
      END IF;
   END PROCESS rx_csm_nextstate_proc;
 
   -----------------------------------------------------------------
   rx_csm_output_proc : PROCESS ( 
      rx_csm_current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      bus_rd <= '0';
      bus_request <= '0';
      bus_we <= '0';
      -- Default Assignment To Internals
      data_en <= '0';

      -- Combined Actions
      CASE rx_csm_current_state IS
         WHEN s_addr7 => 
            bus_rd <= '1';
            bus_request <= '1';
            data_en <= '1';
         WHEN s_data6 => 
            bus_request <=  '1';
         WHEN s_num1 => 
            bus_request <= '1';
         WHEN s_arb0 => 
            bus_request <=  '1';
            data_en <= '1';
            bus_we <= '1';
         WHEN s_arb1 => 
            bus_request <= '1';
         WHEN s_arb2 => 
            bus_rd <= '1';
            bus_request <= '1';
            data_en <= '1';
         WHEN s_data15 => 
            bus_request <=  '1';
         WHEN s_arb3 => 
            bus_request <=  '1';
            data_en <= '1';
            bus_we <= '1';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS rx_csm_output_proc;
 
   -----------------------------------------------------------------
   csm_clocked_proc : PROCESS ( 
      clk
   )
   -----------------------------------------------------------------
   BEGIN
      IF (clk'EVENT AND clk = '1') THEN
         IF (reset = '1') THEN
            csm_current_state <= s1;
         ELSE
            csm_current_state <= csm_next_state;
         END IF;
      END IF;
   END PROCESS csm_clocked_proc;
 
   -----------------------------------------------------------------
   csm_nextstate_proc : PROCESS ( 
      csm_current_state,
      slv_cs,
      slv_we
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default state assignment
      csm_next_state <= csm_current_state;
      CASE csm_current_state IS
         WHEN s1 => 
            IF (slv_we = '1' and slv_cs = '1') THEN 
               csm_next_state <= s2;
            ELSE
               csm_next_state <= s1;
            END IF;
         WHEN s2 => 
            csm_next_state <= s2;
         WHEN OTHERS =>
            csm_next_state <= s1;
      END CASE;
   END PROCESS csm_nextstate_proc;
 
   -- Concurrent Statements
   -- Clocked output assignments
   slv_ack <= slv_ack_cld;
   --added by lampl
   response_en_tx <= '0';
   response_nibble_tx <= (others => '0');
   lock_tx <= '0';
   -- command decoder ----------------------
       cmd_write <= '1' when cmd = X"77" else '0'; -- 'W'
       cmd_blockwrite <= '1' when cmd = X"76" else '0'; -- 'V'
       cmd_read <= '1' when cmd = X"72" else '0';  --'R'
       cmd_blockread <= '1' when cmd = X"62" else '0';  --'B'
       cmd_fiforead <= '1' when cmd = X"66" else '0';  --'F'
       cmd_escape <= '1' when cmd < X"20" else '0'; --space
   
       -- calculate nibble from ASCII-code ------------------------------------
       nibble <= cmd(3 downto 0) when cmd(6) = '0' else cmd(3 downto 0) + "1001";
       bus_dout <=bus_dout_int when data_en = '1' else (others => '0');
       bus_addr <= bus_addr_int when data_en = '1' else (others => '0');
   
   ---calculate ASCII-code from nibble -----------------------------------------
      response_nibble <= response_nibble_rx when lock_rx='1' else
                                      response_nibble_tx; 
      response_int <= to_ascii("0000"&response_nibble);
       response <= response_int;
      response_en <= response_en_rx or response_en_tx;
END fsm;
