-- VHDL Entity IP006_lib.uart_top.symbol
--
-- Created:
--          by - lamplpat.Personal ETM (M00159)
--          at - 11:38:42 04/21/15
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY uart_top IS
   GENERIC( 
      core_clk_freq_g : integer := 50000000;
      baudrate_g      : integer := 9600
   );
   PORT( 
      clk    : IN     std_logic;
      din    : IN     std_logic_vector (7 DOWNTO 0);
      reset  : IN     std_logic;
      rxd    : IN     std_logic;
      we     : IN     std_logic;
      dout   : OUT    std_logic_vector (7 DOWNTO 0);
      rx_ack : OUT    std_logic;
      tx_ack : OUT    std_logic;                      -- transmit acknowledge
      txd    : OUT    std_logic
   );

-- Declarations

END uart_top ;

--
-- VHDL Architecture IP006_lib.uart_top.struct
--
-- Created:
--          by - lamplpat.Personal ETM (M00159)
--          at - 16:30:08 03/23/17
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.1 (Build 8)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY IP006_lib;

ARCHITECTURE struct OF uart_top IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT uart_rx
   GENERIC (
      baudrate_g      : integer := 9600;
      core_clk_freq_g : integer := 50000000
   );
   PORT (
      clk    : IN     std_logic ;
      reset  : IN     std_logic ;
      rxd    : IN     std_logic ;
      dout   : OUT    std_logic_vector (7 DOWNTO 0);
      rx_ack : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT uart_tx
   GENERIC (
      baudrate_g      : integer := 9600;
      core_clk_freq_g : integer := 50000000
   );
   PORT (
      clk    : IN     std_logic ;                    -- core clock
      din    : IN     std_logic_vector (7 DOWNTO 0); -- parallel tx data input
      reset  : IN     std_logic ;                    -- synchronous, active high reset
      we     : IN     std_logic ;                    -- data write enable
      tx_ack : OUT    std_logic ;                    -- transmit acknowledge
      txd    : OUT    std_logic                      -- serial  transmit data
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : uart_rx USE ENTITY IP006_lib.uart_rx;
   FOR ALL : uart_tx USE ENTITY IP006_lib.uart_tx;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   I0 : uart_rx
      GENERIC MAP (
         baudrate_g      => baudrate_g,
         core_clk_freq_g => core_clk_freq_g
      )
      PORT MAP (
         clk    => clk,
         reset  => reset,
         rxd    => rxd,
         dout   => dout,
         rx_ack => rx_ack
      );
   I1 : uart_tx
      GENERIC MAP (
         baudrate_g      => baudrate_g,
         core_clk_freq_g => core_clk_freq_g
      )
      PORT MAP (
         clk    => clk,
         din    => din,
         reset  => reset,
         we     => we,
         tx_ack => tx_ack,
         txd    => txd
      );

END struct;
